### ISSUE TITLE
Results

### ISSUE THREAD

**Issue by ZJG0** [ssloxford/seeing-red#1]
To watch the result of classification，how to use the `results/all.npy`

**Comment by giuliolovisotto** [comment]
Hi @ZJG0, those are multidimensional tables containing Equal Error Rate measurements where each table dimension is described by the `descr.json` contained in the same folder.

For example, if you load `data/results/exp1/all.npy` with numpy (`np.load`) you'll see that it contains a four dimensional matrix, where each dimension is described in  `data/results/exp1/descr.json`, the order of the dimensions is found in the `header` field of that dictionary, I reported here below the content of  `descr.json` for `exp1`.

Specifically, the element `[i, j, k, m]` in that matrix contains the equal error rate measured for the `i`-th cross validation fold, `j`-th classifier, `k`-th aggregation window size and `m`-th user.

Different experiment folders have different `descr.json` files.

```
// /home/data/results/exp1/descr.json
{
  "header": [  // this specifies the order of the dimensions in all.npy
    "fold",
    "clf",
    "window_size",
    "user"
  ],
  "fold": [
    0,
    1
  ],
  "clf": [
    "SVM",
    "GBT",
    "RF"
  ],
  "window_size": [
    1,
    2,
    5,
    10,
    20
  ],
  "user": [
    "12.0",
    "6.0",
    "7.0",
    "13.0",
    "11.0",
    "10.0",
    "4.0",
    "0.0",
    "14.0",
    "1.0",
    "3.0",
    "2.0",
    "9.0",
    "8.0"
  ]
}
```
