### ISSUE TITLE
How to define `max_bpm` if `frame_rate = 30`?

### ISSUE THREAD

**Issue by ChicoQ** [ssloxford/seeing-red#10]
Hi there, thank you for your great work. I've learnt a lot so far. 

By default, my FPS=30 when using iPhone video to record my finger. I'm wondering if frame_rate is changed from 240 to 30, how much the max_bpm would be? 30 or still 120 as your paper suggested? Thank you.

**Comment by hcmturner** [comment]
Hi! The maximum bpm is governed by [Nyquist's theorem](https://en.wikipedia.org/wiki/Nyquist%E2%80%93Shannon_sampling_theorem). at 30FPS you can do 15BPS. We set this max to filter out other noise
