### ISSUE TITLE
IndexError: index 209 is out of bounds for axis 0 with size 200 - feature_extractor.py

### ISSUE THREAD

**Issue by no-name-provide** [ssloxford/seeing-red#3]
Hi,
I am testing the code through some ppg signals of an oximeter saved in a csv in the "extracted" folder. I ran in the order: "signal_preprocessor.py", "signal_beat_separation.py", "signal_fiducial_points_detection.py", "fta_average_beat.py", "signal_beat_fta.py"

but when the program tries to run "feature_extractor.py" to extract the features I get the following error:

```
root @ baa26fd16149: / home / code # python feature_extractor.py
001 (1/9), 00101.json, f_cheating
001 (1/9), 00101.json, f_widths
001 (1/9), 00101.json, f_fft
Traceback (most recent call last):
  File "feature_extractor.py", line 309, in <module>
    ** fextractor ["params"])
  File "feature_extractor.py", line 190, in f_fiducial_points
    dychrotic_notch_value = y [dychrotic_notch_index]
IndexError: index 209 is out of bounds for axis 0 with size 200
```

I tried to change the size of the array to greater than 209 but the problem repeats. Can someone help me?

Thanks.
Sincerely

**Comment by giuliolovisotto** [comment]
Hi, the error means that the `dychrotic_notch_index` found by`hb_fp_detection_20191217` defined in `signal_fiducial_points_detection.py` is wrong, it goes past the length of the heartbeat.

You should spend some time to craft a replacement for `hb_fp_detection_20191217` that works reliably with your data, unfortunately the way it is now it works *ok* on our data. Once you have re-written that, re-run the scripts from fiducial points detection onwards with `--force-redo`.

Anyway, I have patched this with 9107486079f07f6f2d92f34c19816d64e5a17ee1, re-run from `signal_fiducial_points_detection.py` let me know if you still have problems.
